void print_help(void){
	printf("\n%s", STR_VALID_COMMANDS);
	printf("\n%s %s %s %s %s %s %s", STR_HELP_1, STR_NAME_1, STR_PROTOCOL_1, STR_INFILE_1, STR_OUTFILE_1, STR_LOGFILE_1, STR_MAXLEN_1);
	printf("\n%s %s %s %s %s %s %s", STR_HELP_2, STR_NAME_2, STR_PROTOCOL_2, STR_INFILE_2, STR_OUTFILE_2, STR_LOGFILE_2, STR_MAXLEN_2);
	printf("\n\n%s", STR_DESCRIPTION_ARG);
	printf("\n[%s, %s]", STR_HELP_1, STR_HELP_2);
	printf("\n%s", TXT_HELP);
	printf("\n[%s, %s]", STR_NAME_1, STR_NAME_2);
	printf("\n%s", TXT_NAME);
	printf("\n[%s, %s]", STR_PROTOCOL_1, STR_PROTOCOL_2);
	printf("\n%s", TXT_PROTOCOL);
	printf("\n[%s, %s]", STR_INFILE_1, STR_INFILE_2);
	printf("\n%s", TXT_INFILE);
	printf("\n[%s, %s]", STR_OUTFILE_1, STR_OUTFILE_2);
	printf("\n%s", TXT_OUTFILE);
	printf("\n[%s, %s]", STR_LOGFILE_1, STR_LOGFILE_2);
	printf("\n%s", TXT_LOGFILE);
	printf("\n[%s, %s]", STR_MAXLEN_1, STR_MAXLEN_2);
	printf("\n%s", TXT_MAXLEN);
	printf("\n\n%s", STR_IMPLEMENTATION);
	printf("\n\n%s:", STR_VALID_EX);
	printf("\n%s", VALID_EX_HELP_1);
	printf("\n%s", VALID_EX_HELP_2);
	printf("\n%s", VALID_EX_NAME_1);
	printf("\n%s", VALID_EX_NAME_2);
	printf("\n%s", VALID_EX_PROTOCOL_1);
	printf("\n%s", VALID_EX_PROTOCOL_2);
	printf("\n%s", VALID_EX_INFILE_1);
	printf("\n%s", VALID_EX_INFILE_2);
	printf("\n%s", VALID_EX_OUTFILE_1);
	printf("\n%s", VALID_EX_OUTFILE_2);
	printf("\n%s", VALID_EX_LOGFILE_1);
	printf("\n%s", VALID_EX_LOGFILE_2);
	printf("\n%s", VALID_EX_MAXLEN_1);
	printf("\n%s", VALID_EX_MAXLEN_2);
	printf("\n\n%s:", STR_INVALID_EX);
	printf("\n%s", INVALID_EX_HELP_1);
	printf("\n%s", INVALID_EX_HELP_2);
	printf("\n%s", INVALID_EX_NAME_1);
	printf("\n%s", INVALID_EX_NAME_2);
	printf("\n%s", INVALID_EX_PROTOCOL_1);
	printf("\n%s", INVALID_EX_PROTOCOL_2);
	printf("\n%s", INVALID_EX_INFILE_1);
	printf("\n%s", INVALID_EX_INFILE_2);
	printf("\n%s", INVALID_EX_OUTFILE_1);
	printf("\n%s", INVALID_EX_OUTFILE_2);
	printf("\n%s", INVALID_EX_LOGFILE_1);
	printf("\n%s", INVALID_EX_LOGFILE_2);
	printf("\n%s", INVALID_EX_MAXLEN_1);
	printf("\n%s", INVALID_EX_MAXLEN_2);
}