#ifndef HELP__H
#define HELP__H 1

#include <stdio.h>

#define TXT_HELP "Shows help."
#define STR_HELP_1 "-h"
#define STR_HELP_2 "--help"
#define TXT_NAME "Indicates metadata name."
#define STR_NAME_1 "-n"
#define STR_NAME_2 "--name"
#define TXT_PROTOCOL "Indicates the protocol. It can be a NMEA, UBX or AUTO."
#define STR_PROTOCOL_1 "-p"
#define STR_PROTOCOL_2 "--protocol"
#define TXT_INFILE "Indicates input file name. If argument is only '-', input file is stdin. In case this argument is not entered, program returns error."
#define STR_INFILE_1 "-i"
#define STR_INFILE_2 "--infile"
#define TXT_OUTFILE "Indicates output file name. If argument is only '.', output file is stdout. In case this argument is not entered, program returns error." 
#define STR_OUTFILE_1 "-l"
#define STR_OUTFILE_2 "--logfile"
#define TXT_LOGFILE "Indicates file name which will be used for logs. If argument is only '-', logfile is stderr. In case this argument is not entered, program returns error."
#define STR_LOGFILE_1 "-l"
#define STR_LOGFILE_2 "--logfile"
#define TXT_MAXLEN "Indicates maximum messages amount that can be stored in a list."
#define STR_MAXLEN_1 "-m"
#define STR_MAXLEN_2 "--maxlen"

#define STR_VALID_COMMANDS "LIST OF COMMAND-LINE VALID COMMANDS "
#define STR_DESCRIPTION_ARG "DESCRIPTION OF ARGUMENTS"
#define STR_IMPLEMENTATION "IMPLEMENTATION"
#define STR_VALID_EX "Valid Examples"
#define STR_INVALID_EX "Invalid Examples"

#define VALID_EX_HELP_1 "-h"
#define VALID_EX_HELP_2 "--help"
#define VALID_EX_NAME_1 "-n monkey"
#define VALID_EX_NAME_2 "--name monkey"
#define VALID_EX_PROTOCOL_1 "-p nmea"
#define VALID_EX_PROTOCOL_2 "--protocol ubx"
#define VALID_EX_INFILE_1 "-i fiuba.ubx"
#define VALID_EX_INFILE_2 "--infile jungle.nmea"
#define VALID_EX_OUTFILE_1 "-o -"
#define VALID_EX_OUTFILE_2 "--outfile output_file.gpx"
#define VALID_EX_LOGFILE_1 "-l logs.txt"
#define VALID_EX_LOGFILE_2 "--logfile notifications.txt"
#define VALID_EX_MAXLEN_1 "-m 100"
#define VALID_EX_MAXLEN_2 "--maxlen 50"
#define INVALID_EX_HELP_1 "-help"
#define INVALID_EX_HELP_2 "--h"
#define INVALID_EX_NAME_1 "-n monkey%%#"
#define INVALID_EX_NAME_2 "--name"
#define INVALID_EX_PROTOCOL_1 "-p "
#define INVALID_EX_PROTOCOL_2 "--protocol monkey"
#define INVALID_EX_INFILE_1 "-infile safari.ubx"
#define INVALID_EX_INFILE_2 "--infile "
#define INVALID_EX_OUTFILE_1 "-outfile "
#define INVALID_EX_OUTFILE_2 "--o of.ubx"
#define INVALID_EX_LOGFILE_1 "-logfile "
#define INVALID_EX_LOGFILE_2 "--l logs.txt "
#define INVALID_EX_MAXLEN_1 "-m a12"
#define INVALID_EX_MAXLEN_2 "--maxlen 100Q"

void print_help();

#endif